output "key_id" {
  description = "A UUID used to uniquely identify this password credential."
  value       = azuread_service_principal_password.service_principal_password.key_id
}

output "value" {
  description = "The password for this service principal, which is generated by Azure Active Directory."
  value       = azuread_service_principal_password.service_principal_password.value
}
