variable "provider_name" {
  description = "The name of the SSO provider."
  type        = string
}

variable "oauth2_settings_block" {
  description = "The OAuth2 settings set."
  type = object({
    client_id = string
    allow_assign_grafana_admin = optional(bool)
    allow_sign_up = optional(bool)
    allowed_domains = optional(list(string))
    allowed_groups = optional(list(string))
    allowed_organizations = optional(list(string))
    api_url = optional(string)
    auth_style = optional(string)
    auth_url = optional(string)
    auto_login = optional(bool)
    client_secret = optional(string)
    custom = optional(map(string))
    define_allowed_groups = optional(bool)
    define_allowed_teams_ids = optional(bool)
    email_attribute_name = optional(string)
    email_attribute_path = optional(string)
    empty_scopes = optional(bool)
    enabled = optional(bool)
    groups_attribute_path = optional(string)
    id_token_attribute_name = optional(string)
    login_attribute_path = optional(string)
    name = optional(string)
    name_attribute_path = optional(string)
    org_attribute_path = optional(string)
    org_mapping = optional(string)
    role_attribute_path = optional(string)
    role_attribute_strict = optional(bool)
    scopes = optional(string)
    signout_redirect_url = optional(string)
    skip_org_role_sync = optional(bool)
    team_ids = optional(string)
    team_ids_attribute_path = optional(string)
    teams_url = optional(string)
    tls_client_ca = optional(string)
    tls_client_cert = optional(string)
    tls_client_key = optional(string)
    tls_skip_verify_insecure = optional(bool)
    token_url = optional(string)
    use_pkce = optional(bool)
    use_refresh_token = optional(bool)
  })
  default = null
}

variable "saml_settings_block" {
  description = "The SAML settings set."
  type = object({
    allow_idp_initiated = optional(bool)
    allow_sign_up = optional(bool)
    allowed_organizations = optional(string)
    assertion_attribute_email = optional(string)
    assertion_attribute_groups = optional(string)
    assertion_attribute_login = optional(string)
    assertion_attribute_name = optional(string)
    assertion_attribute_org = optional(string)
    assertion_attribute_role = optional(string)
    auto_login = optional(bool)
    certificate = optional(string)
    certificate_path = optional(string)
    client_id = optional(string)
    client_secret = optional(string)
    enabled = optional(bool)
    force_use_graph_api = optional(bool)
    idp_metadata = optional(string)
    idp_metadata_path = optional(string)
    idp_metadata_url = optional(string)
    max_issue_delay = optional(string)
    metadata_valid_duration = optional(string)
    name = optional(string)
    name_id_format = optional(string)
    org_mapping = optional(string)
    private_key = optional(string)
    private_key_path = optional(string)
    relay_state = optional(string)
    role_values_admin = optional(string)
    role_values_editor = optional(string)
    role_values_grafana_admin = optional(string)
    role_values_none = optional(string)
    role_values_viewer = optional(string)
    signature_algorithm = optional(string)
    single_logout = optional(bool)
    skip_org_role_sync = optional(bool)
    token_url = optional(string)
  })
  default = null
}