name: Demo Workflow Example

on:
  workflow_dispatch:
    push:
      branches:
        - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run the scripts
        run: |
          ls -la .
